name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main  # Cambia a 'master' si tu rama principal es esa

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --release

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLPWA_F201E }}"
          channelId: live
          projectId: clpwa-f201e
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
